table Dim_Date
	lineageTag: 057c5093-1f3a-43b3-9200-714a20558503

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 03d73cc8-37af-495b-8912-51099ca058ec
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: #,0
		lineageTag: a66c28a0-0cd3-47af-a6b7-822fddadd2e6
		summarizeBy: sum
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: #,0
		lineageTag: 1d375844-2d15-4112-9ba2-78610d7ea473
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: string
		lineageTag: 8aa24e44-c5bc-4beb-b04e-0df663ed04da
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: #,0
		lineageTag: 1dad0a12-e65c-415b-bab3-531ca3a5780c
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 969d9e58-9a64-46ff-9d4c-45d217b3664e
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column month_year
		dataType: string
		lineageTag: 9578ec61-37f2-4705-a7f4-37053aeb17ca
		summarizeBy: none
		sourceColumn: month_year

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: string
		lineageTag: 457d1fae-29c7-40ca-8f8b-8a1816c5ac02
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column is_month_end
		dataType: boolean
		lineageTag: 7cf289f4-94b8-4867-b3d0-4fa473590ff2
		summarizeBy: none
		sourceColumn: is_month_end

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\kiran\OneDrive\Documents\GitHub\Bluestock_internship\dashboard\data\dim_date.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"date", type date}, {"date_key", Int64.Type}, {"year", Int64.Type}, {"quarter", type text}, {"month", Int64.Type}, {"month_name", type text}, {"month_year", type text}, {"fiscal_year", type text}, {"is_month_end", type logical}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

